ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Gradle Helm Plugin

This is a suite of Gradle plugins for building, publishing and managing https://www.helm.sh/[Helm] charts.

NOTE: Starting with version 1.0.0, the plugins require Helm 3.+.


== Features

* Gradle task types for common Helm CLI commands
* Build, package and publish Helm charts using a declarative Gradle DSL
* Resolve placeholders like `${chartVersion}` from chart source files before packaging
* Resolve dependencies between charts using Gradle artifact dependencies
* Install, upgrade and uninstall releases to/from a Kubernetes cluster


== Requirements

* Gradle 5.1 or higher
* JDK 1.8 or higher (for running Gradle)
* Helm command-line client 3.+


== Quick Start

Apply the `org.unbroken-dome.helm` plugin to your Gradle project:

.build.gradle
[source,groovy]
----
plugins {
  id 'org.unbroken-dome.helm' version '1.2.1'
}
----


Put your Helm chart sources into `src/main/helm`:

----
📂 (project root)
    📂 src
        📂 main
            📂 helm
                📂 templates
                    📄 ...
                📄 Chart.yaml
                📄 values.yaml
----

Use the `helmPackage` task to build your chart.


== Further Documentation

* https://unbroken-dome.github.io/projects/gradle-helm-plugin/[User Manual]
* https://unbroken-dome.github.io/projects/gradle-helm-plugin/dokka/gradle-helm-plugin/[API/DSL Documentation]
