= Filtering Chart Sources

The plugin includes a _filtering_ step that will resolve placeholders in certain chart files before the chart
is packaged.

This is most useful to insert the name and version into the chart, because they will often correspond to the
Gradle project's name and version:

.Chart.yaml
[source,yaml]
----
apiVersion: v1
name: ${chartName}
version: ${chartVersion}
appVersion: ${projectVersion}
----

The following placeholders are automatically available based on the corresponding properties of the chart in
the DSL. You can also define additional placeholders and their values using the `filtering.values` property (see below).

[cols="1,3"]
|===
| Placeholder | Content
| `chartName` | The chart name, as set by the `HelmChart.chartName` property in the build script
| `chartVersion` | The chart version, as set by the `HelmChart.chartVersion` property in the build script
| `projectVersion` | The `version` of the Gradle `Project` (at the time the filtering task is executed)
|===

NOTE: Only the files _Chart.yaml_, _requirements.yaml_ and _values.yaml_ are filtered this way. The actual templates
in the chart are not filtered; you should use Helm's templating constructs instead.


== Configure the Filtering Step

You can fine-tune the filtering process by modifying the `filtering` block, which is available both directly inside
the `helm` block, as well as each chart. The chart-level filtering inherits from the global filtering but will
override properties if they are defined in both places:

[source,groovy,role="primary"]
.Groovy
----
helm {
    filtering {
        // This value will be resolvable in all charts' YAML files as ${authorName}
        values.put 'authorName', 'A. U. Thor'
    }

    charts {
        main {
            filtering {
                // add a custom value that can be resolved only inside this chart's YAML files.
                values.put 'dockerImage', 'busybox'
            }
        }
    }
}
----

[source,kotlin,role="secondary"]
.Kotlin
----
helm {
    filtering {
        // This value will be resolvable in all charts' YAML files as ${authorName}
        values.put("authorName", "A. U. Thor")
    }

    charts {
        main {
            filtering {
                // add a custom value that can be resolved only inside this chart's YAML files.
                values.put("dockerImage", "busybox")
            }
        }
    }
}
----

You can also pass a `Provider` or `Property` as the value; in this case it will be resolved lazily when the filtering
task runs.

The following properties are available in the `filtering` block:

|===
| Property | Type | Default Value | Description

| enabled | `boolean` | `true` | Enables or disables the entire filtering step.
| placeholderPrefix | `String` | `${` | The string that marks the end of a resolvable placeholder inside the filtered YAML files.
| placeholderSuffix | `String` | `}` | The string that marks the end of a resolvable placeholder inside the filtered YAML files.
| values | `Map` | | The values to be resolved in placeholders.
|===

INFO: `values` is a `MapProperty` which merges the values from different levels of `filtering` blocks. That means
you can add some values in the global `helm.filtering` block, add some more inside the individual chart's `filtering`
block, and they will all be available for the placeholder resolution.
