= Filtering Chart Sources

The plugin includes a _filtering_ step that will resolve placeholders in certain chart files before the chart
is packaged.

Filtered files are processed using a Groovy
link:https://docs.groovy-lang.org/latest/html/api/groovy/text/SimpleTemplateEngine.html[SimpleTemplateEngine]. Filter
expressions are Groovy expressions enclosed in `${` and `}`, for example `${chartName}`.

TIP: If you have actual `$` characters in these files, you can escape them as `\$` so they are not interpreted as a filter expression.

The following placeholders are automatically available based on the corresponding properties of the chart in
the DSL. You can also define additional placeholders and their values using the `filtering.values` property (see below).

[cols="1,3"]
|===
| Placeholder | Content
| `chartName` | The chart name, as set by the `HelmChart.chartName` property in the build script
| `chartVersion` | The chart version, as set by the `HelmChart.chartVersion` property in the build script
| `projectVersion` | The `version` of the Gradle `Project` (at the time the filtering task is executed)
|===

TIP: The `name` and `version` in the Chart.yaml are automatically replaced based on the chart information from the
Gradle script. You do not need to add filter expressions for these.

== Enable or Disable Filtering

The filtering is enabled by default. You can set the `filtering.enabled` property to `false` if you would not like
the chart to be filtered. This can be done either on the project level or the chart level:

[source,groovy,role="primary"]
.Groovy
----
helm {
    // Disable filtering by default
    filtering.enabled = false

    charts {
        chart1 {
            // filtering will be enabled for this chart
            filtering.enabled = true
        }
        chart2 {
            // filtering will be disabled for this chart (inheriting settings from project level)
        }
    }
}
----

[source,kotlin,role="secondary"]
.Kotlin
----
helm {
    // Disable filtering by default
    filtering.enabled.set(false)

    charts {
        create("chart1") {
            // filtering will be enabled for this chart
            filtering.enabled.set(true)
        }
        create("chart2") {
            // filtering will be disabled for this chart (inheriting settings from project level)
        }
    }
}
----

== Configure Which Files are Filtered

By default, filtering applies only to the `Chart.yaml`, `requirements.yaml` and `values.yaml` files directly
in the chart directory, but not to any templates or other files in the chart.

TIP: If templates in a chart need to be dynamically modified based on the Gradle script, consider adding a value
  to the `values.yaml` file that uses a filtering expression, and then use that value in your templates using
  Helm's templating constructs.

The `filtering` block has a `filePatterns` property which holds the (Ant-style) patterns of files to be filtered.
If this list is empty, it is equivalent to the pattern `*` so _all_ files in the chart will be filtered.

[source,groovy,role="primary"]
.Groovy
----
helm {
    filtering {
        // apply filtering to all files in the chart
        filePatterns.add('*')
    }
}
----

[source,kotlin,role="secondary"]
.Kotlin
----
helm {
    filtering {
        // apply filtering to all files in the chart
        filePatterns.add("*")
    }
}
----


== Supply Additional Values

Use the `filtering.values` property to define additional values to be available in filtering expressions.
Again, values may be specified in the project-level `filtering` block, as well as on a `filtering` block for an
individual chart. Project-level and chart-level values are merged, with the chart-level values having precedence
if a value is defined in both places.

[source,groovy,role="primary"]
.Groovy
----
helm {
    filtering {
        // This value will be resolvable in all charts' YAML files as ${authorName}
        values.put 'authorName', 'A. U. Thor'
    }

    (charts) {
        "main" {
            filtering {
                // add a custom value that can be resolved only inside this chart's YAML files.
                values.put 'dockerImage', 'busybox'
            }
        }
    }
}
----

[source,kotlin,role="secondary"]
.Kotlin
----
helm {
    filtering {
        // This value will be resolvable in all charts' YAML files as ${authorName}
        values.put("authorName", "A. U. Thor")
    }

    charts {
        main {
            filtering {
                // add a custom value that can be resolved only inside this chart's YAML files.
                values.put("dockerImage", "busybox")
            }
        }
    }
}
----

TIP: You can also pass a `Provider` or `Property` as the value; in this case it will be resolved lazily when the filtering
task runs.


=== Example: Pass the JIB Docker Image Name and Version

Many Helm charts use the following conventional structure in their `values.yaml` to specify the Docker image to be
used in Kubernetes deployments:

[source,yaml]
.values.yaml
----
image:
  repository: "gcr.io/awesome-project/awesome-image"
  tag: "1.2.3"
----

If the Docker image is built with JIB in the same project, we can avoid the repetition (which is bound to cause silly
copy & paste errors eventually) and pass the values from Gradle instead:

[source,groovy,role="primary"]
.build.gradle
----
helm {
    filtering {
        values.put 'imageRepository', jib.to.image
        values.put 'imageTag', jib.to.tags.first()
    }
}
----

[source,kotlin,role="secondary"]
.build.gradle.kts
----
helm {
    filtering {
        values.put("imageRepository", jib.to.image)
        values.put("imageTag", jib.to.tags.first())
    }
}
----

And then refer to these values in the `values.yaml` file:

[source,yaml]
.values.yaml
----
image:
  repository: ${imageRepository}
  tag: ${imageTag}
----


=== Values from Files

Values can also be read from the contents of files; use the `filtering.fileValues` property for this. The following
example would generate a RSA private key using `openssl` and then pass it to the filtering:

[source,groovy,role="primary"]
.Groovy
----
def rsaKeyFile = objects.file()
    .fileValue(file("$buildDir/rsa.key"))

task generateRsaKey(type: Exec) {
    // Declare the file as a task output so that task dependencies are set up by Gradle
    outputs.file rsaKeyFile
    executable = 'openssl'
    arg 'genrsa', '-out', rsaKeyFile.get()
}

helm.filtering {
    fileValues.put 'rsaKey', rsaKeyFile
}
----

[source,kotlin,role="secondary"]
.Kotlin
----
val rsaKeyFile = objects.file()
    .fileValue(file("$buildDir/rsa.key"))

tasks.create("generateRsaKey", Exec::class) {
    // Declare the file as a task output so that task dependencies are set up by Gradle
    outputs.file(rsaKeyFile)
    executable = "openssl"
    arg("genrsa", "-out", rsaKeyFile.get())
}

helm.filtering {
    fileValues.put("rsaKey", rsaKeyFile)
}
----

Afterwards, we can use this value in our `values.yaml` file (note that the value contains newlines, so we need
to do some processing for correct YAML indentation):

[source,yaml]
.values.yaml
----
rsaKey: |
  ${ rsaKey.collectReplacements { it == '\n' ? '\n    ' : null } }
----
