= Linting Charts

The default workflow for building and packaging a Helm chart includes a lint step, which is
performed by the `HelmLint` task and maps to a `helm lint` CLI call.

Both the global `helm` DSL block and each `chart` block provide a nested `lint` block, where you
can fine-tune linting on a global or chart level. Each chart will inherit the global configuration
and can selectively override certain aspects of it.

[source,groovy,role="primary"]
.Groovy
----
helm {

    // The global lint configuration applies to all charts
    lint {
        // treat linter warnings as errors (failing the build)
        strict = true

        // also lint dependent charts
        withSubcharts = true
    }

    charts {
        main {
            // This configures linting only for the main chart
            lint {
                // disable strict linting only for this chart
                strict = false
            }
        }
    }
}
----

[source,kotlin,role="secondary"]
.Kotlin
----
helm {

    // The global lint configuration applies to all charts
    lint {
        // treat linter warnings as errors (failing the build)
        strict.set(true)

        // also lint dependent charts
        withSubcharts.set(true)
    }

    charts {
        create("main") {
            // This configures linting only for the main chart
            lint {
                // disable strict linting only for this chart
                strict.set(false)
            }
        }
    }
}
----


== Passing Values to the Linter

You can pass values to the linter using the `values`, `fileValues` and `valueFiles`.

* `values` contains values to be passed directly (CLI option: `--set` or `--set-string`)
* `fileValues` contains values to be read from files (CLI option: `--set-file`)
* `valueFiles` contains a list of files that contain values in YAML format (CLI option: `--values`)

Passing values to `helm lint` may be necessary to avoid warnings if you use the `required` function in your Helm
templates (see https://github.com/helm/helm/issues/2347[Helm issue #2347]). Also, it can be useful if
you have conditional templates which would not be rendered when using the default values
from values.yaml.

[TIP]
`helm lint` does not actually perform a syntactic analysis of your charts; instead it renders
the template internally (just as `helm template` would do) and checks the resulting YAML for
correctness.

Values and value files defined in the global `lint` block are automatically inherited by
each chart; however a chart can add additional values or value files.

[source,groovy,role="primary"]
.Groovy
----
helm {

    lint {
        valueFiles.from 'src/test/helm/helm-lint-global.yaml'
    }

    charts {
        main {
            lint {
                valueFiles.from 'src/test/helm/helm-lint-main.yaml'
                values.put 'foo', 'bar'
            }
        }
    }
}
----

[source,kotlin,role="secondary"]
.Kotlin
----
helm {

    lint {
        valueFiles.from("src/test/helm/helm-lint-global.yaml")
    }

    (charts) {
        "main" {
            lint {
                valueFiles.from("src/test/helm/helm-lint-main.yaml")
                values.put("foo", "bar")
            }
        }
    }
}
----


== Disable the Lint Step

You can disable the lint step altogether by setting the `lint.enabled` property to `false`. This
works on a global as well as on a chart level. (Again, the chart setting is inherited from the
global setting).

[source,groovy,role="primary"]
.Groovy
----
helm {

    lint {
        // disable linting by default
        enabled = false
    }

    charts {
        main {
            // enable linting for the main chart
            lint.enabled = true
        }
    }
}
----

[source,kotlin,role="secondary"]
.Kotlin
----
helm {

    lint {
        // disable linting by default
        enabled.set(false)
    }

    (charts) {
        "main" {
            // enable linting for the main chart
            lint.enabled.set(true)
        }
    }
}
----


== Using Multiple Lint Configurations

Many charts use conditional expressions like `{{ if }} ... {{ else }}` to include parts of a template based on the
supplied values. This can make it difficult to completely lint the chart in one go, because often there is
no combination of values that can be supplied to the linter that would really render everything in the chart.

The plugin addresses this by supporting multiple linter configurations: Inside the `lint` block for a chart,
you have a container for `configurations`, and each configuration can have its own `values`, `fileValues` and
`valueFiles`. Each lint configuration will give rise to a separate `HelmLint` task that will run the linter with
the specified input.

The `values`, `fileValues` and `valueFiles` for each lint configuration are merged with (and can selectively
override) the corresponding properties from the chart's `lint` block and the global `lint` block, allowing you to
have a hierarchy of common and more specialized values.

[source,groovy,role="primary"]
.Groovy
----
helm {
    lint {
        // This values file will be used for ALL lint configurations in ALL charts
        valueFiles.from 'src/test/helm/helm-lint-all.yaml'
    }

    charts {
        main {
            lint {
                // This values file will be used for ALL lint configurations in this chart
                valueFiles.from 'src/test/helm/helm-lint-main-common.yaml'

                configurations {
                    basic {
                        // This values file will be used for the basic configuration only
                        valueFiles.from 'src/test/helm/helm-lint-main-basic.yaml'
                    }
                    advanced {
                        // This value file will be used for the advanced configuration only
                        valueFiles.from 'src/test/helm/helm-lint-main-advanced.yaml'
                    }
                }
            }
        }
    }
}
----

[source,kotlin,role="secondary"]
.Kotlin
----
helm {
    lint {
        // This value file will be used for ALL lint configurations in ALL charts
        valueFiles.from("src/test/helm/helm-lint-all.yaml")
    }

    charts {
        "main" {
            lint {
                // This value file will be used for ALL lint configurations in this chart
                valueFiles.from("src/test/helm/helm-lint-main-common.yaml")

                configurations {
                    register("basic") {
                        // This value file will be used for the basic configuration only
                        valueFiles.from("src/test/helm/helm-lint-main-basic.yaml")
                    }
                    register("advanced") {
                        // This value file will be used for the advanced configuration only
                        valueFiles.from("src/test/helm/helm-lint-main-advanced.yaml")
                    }
                }
            }
        }
    }
}
----

Now, running `helmLint<Chart>Chart` (or other tasks that depend on it, such as `helmPackage`) will invoke `helm lint`
for each configuration, by way of a separate `HelmLint` task per configuration that it depends on.

You can also run the linter for a single configuration using the `helmLint<Chart>Chart<Configuration>`.

NOTE: If you do not add any lint configurations, the plugin automatically creates a single configuration named
"default" with no additional values.
