= Plugins

The _gradle-helm-plugin_ library provides several Gradle plugins, with different use cases for each.

All plugins IDs are prefixed the namespace `com.citi`.


== `helm-commands`

This plugin does little more than add the plugin library to your build's classpath so you can define tasks for
 various Helm CLI commands. It creates the `helm` DSL block which you can use to configure common settings
 for all tasks, like the Helm home path and the Kubecontext. Apart from this, it does not create any tasks
 automatically.

Use this if you want to use Helm CLI commands directly as tasks, without any of the declarative DSL that the `helm`
 plugin offers.

[source,groovy,role="primary",subs="+attributes"]
.Groovy
----
plugins {
    id 'com.citi.helm-commands' version '{project-version}'
}
----

[source,kotlin,role="secondary",subs="+attributes"]
.Kotlin
----
plugins {
    id("com.citi.helm-commands") version "{project-version}"
}
----

All the other plugins imply `helm-commands`, so you don't need to apply this plugin if you use any of the others.



== `helm`

This is the main plugin of the suite. It enables a variety of extra DSL blocks inside `helm`, for example `charts`
 and `repositories`.

[source,groovy,role="primary",subs="+attributes"]
.Groovy
----
plugins {
    id 'com.citi.helm' version '{project-version}'
}
----

[source,kotlin,role="secondary",subs="+attributes"]
.Kotlin
----
plugins {
    id("com.citi.helm") version "{project-version}"
}
----


== `helm-publish`

Use this plugin to publish charts to a remote chart repository like ChartMuseum.

It enables the `helm.publishing` DSL block and adds publishing tasks for each chart.

[source,groovy,role="primary",subs="+attributes"]
.Groovy
----
plugins {
    id 'com.citi.helm-publish' version '{project-version}'
}
----

[source,kotlin,role="secondary",subs="+attributes"]
.Kotlin
----
plugins {
    id("com.citi.helm-publish") version "{project-version}"
}
----


== `helm-releases`

Use this plugin to manage Helm releases (install/upgrade/uninstall) on a remote Kubernetes cluster.

It enables the `helm.releases` DSL block, where you can declare your releases using Gradle DSL, referencing either
 Helm charts built using the other projects, or existing charts from a Helm repository.

[source,groovy,role="primary",subs="+attributes"]
.Groovy
----
plugins {
    id 'com.citi.helm-releases' version '{project-version}'
}
----

[source,kotlin,role="secondary",subs="+attributes"]
.Kotlin
----
plugins {
    id("com.citi.helm-releases") version "{project-version}"
}
----
